proj/ots/urls.py

from django.urls import path
from ots.views import*
from django.contrib.auth import views as auth_views
app_name='ots'
urlpatterns = [
    path('',welcome,name='welcome'),
    path('new-candidate',CandidateRegistrationForm,name='registrationForm'),
    path('store-candidate',CandidateRegistration,name='storeCandidate'),
    path('login',loginView,name='login'),
    path('home',CandidateHome,name="home"),
    path('test-paper',testPaper,name="testpaper"),
    path('calculate-result',CalculateTestResult,name="calculate_test"),
    path('test-history',testResultHistory,name="testHistory"),
    path('result',showTestResult,name="result"),
    path('logout',logoutView,name='logout'),
]

proj/proj/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ots/',include('ots.urls')),
]

proj/ots/models.py
from django.db import models
class Candidate(models.Model):
    username=models.CharField(primary_key=True,max_length=30)
    password=models.CharField(null=False,max_length=20)
    name=models.CharField(null=False,max_length=30)
    test_attempted=models.IntegerField(default=0)
    points=models.FloatField(default=0.0)
class Question(models.Model):
    q_id=models.BigAutoField(primary_key=True,auto_created=True)
    que=models.TextField()
    a=models.CharField(max_length=255)
    b=models.CharField(max_length=255)
    c=models.CharField(max_length=255)
    d=models.CharField(max_length=255)
    ans=models.CharField(max_length=2)
class Result(models.Model):
    resultid=models.BigAutoField(primary_key=True,auto_created=True)
    username=models.ForeignKey(Candidate,on_delete=models.CASCADE)
    date=models.DateField(auto_now=True)
    time=models.TimeField(auto_now=True)
    attempt=models.IntegerField()
    right=models.IntegerField()
    wrong=models.IntegerField()
    points=models.FloatField()
# Create your models here.

proj/ots/views.py
from django.shortcuts import render
from django.urls import path,include
from django.contrib import admin
from django.http import HttpResponse,HttpResponseRedirect
from ots.models import*
from proj import settings
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate,login
from django.core.mail import send_mail
import random
def welcome(request):
    return render(request,'index.html')
def CandidateRegistrationForm(request):
    return render(request, 'registration_form.html')
def CandidateRegistration(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['pass1']
        email=request.POST['email']
        if(username==""  or (request.POST['pass1']=="" or request.POST['name']=="")):
          userStatus=0
        elif(len(Candidate.objects.filter(username=username))):
            userStatus=1
        elif(request.POST['pass1']!=request.POST['pass2']):
            userStatus=4            
        else:
            candidate=Candidate()
            candidate.username=username
            candidate.password=request.POST['pass1']
            candidate.name=request.POST['name']
            candidate.save()
            my_user=User.objects.create_user(username,email,password)
            my_user.save()
            userStatus=2
            from_email=settings.EMAIL_HOST_USER
            subject="welcome to ots"
            message="heelo"
            to_list=[my_user.email]
            send_mail(subject,message,from_email,to_list,fail_silently=True)
    else:
        userStatus=3
    context={
       'userStatus':userStatus
    }
    return render(request,'registration.html',context)


def loginView(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        candidate=Candidate.objects.filter(username=username,password=password)
        if(len(candidate)==0):
            loginError="Invalid Username or Password"
            res=render(request,'login.html',{'loginError':loginError})
        else:
            #login succesful#
            request.session['username']=candidate[0].username
            request.session['name']=candidate[0].name
            res=HttpResponseRedirect("home")
    else:
       res=render(request,'login.html')
    return res
def CandidateHome(request):
    if 'name' not in request.session.keys():
        res= HttpResponseRedirect("login")
    else:
        return render(request,"home.html")

def testPaper(request):
   if 'name' not in request.session.keys():
       res= HttpResponseRedirect("login")
   n=int(request.GET['n'])
   question_pool=list(Question.objects.all())
   random.shuffle(question_pool)
   questions_list=question_pool[:n]
   context={'questions':questions_list}
   res= render(request,"test_paper.html",context)
   return res
def CalculateTestResult(request):
    if 'name' not in request.session.keys():
        res= HttpResponseRedirect("login")
    total_attempt=0
    total_right=0
    total_wrong=0
    qid_list=[]
    for k in request.POST:
        if k.startswith('qno'):
            qid_list.append(int(request.POST[k]))
    for n in qid_list:
        question=Question.objects.get(q_id=n)
        try:
            if question.ans==request.POST['q'+str(n)]:
                total_right+=1
            else:
                total_wrong+=1
            total_attempt+=1
        except:
            pass
    points=(total_right-total_wrong)/len(qid_list)*10
    result=Result()
    result.username=Candidate.objects.get(username=request.session['username'])
    result.attempt=total_attempt
    result.right=total_right
    result.wrong=total_wrong
    result.points=points
    result.save()
    #update candidate table#
    candidate=Candidate.objects.get(username=request.session['username'])
    candidate.test_attempted+=1
    candidate.points=(candidate.points*(candidate.test_attempted-1)+points)/candidate.test_attempted
    candidate.save()
    return HttpResponseRedirect('result')
def  testResultHistory(request):
    if 'name' not in request.session.keys():
        res= HttpResponseRedirect("login")
    candidate=Candidate.objects.filter(username=request.session['username'])
    results=Result.objects.filter(username_id=candidate[0].username)
    context={
        'candidate':candidate[0],'results':results
    }
    res=render(request,'candidate_history.html',context)
    return res
def showTestResult(request):
    if 'name' not in request.session.keys():
        res= HttpResponseRedirect("login")
    result=Result.objects.filter(resultid=Result.objects.latest('resultid').resultid,username_id=request.session['username'])
    context={
        'results':result
    }
    res=render(request,'show_result.html',context)
    return res
def logoutView(request):
    if 'name' in request.session.keys():
        del request.session['username']
        del request.session['name']
    return HttpResponseRedirect("login")
# Create your views here.

proj/ots/templates/candidate_history.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        *{
            margin: 0;
            box-sizing: border-box;
        }
    #header{
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding-left: 0px ;
    padding-top: 20px;
    padding-bottom: 30px;
    background-color: aliceblue;
    box-shadow: 0 5px 15 px regba(0,0,0,0.6);
    /*to make navbar sticky*/
    z-index: 999;
    position: sticky;
    top:0;
    left:0;
}
#navbar{
    display: flex;
    align-items: center;
    justify-content: center;
}
#navbar li {
    text-decoration: none;
    list-style: none;
    padding: 0 100px;
    
}
#navbar li a{
    display: flex;
    text-decoration: none;
    font-size: 18px;
    font-weight: 600;
    font-size: 25PX;
    color: #f64C72;
    transition: 0.3s ease;
}
#navbar li a:hover{
    color: darkblue;
}
.logo{
   font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-weight: bold;
    font-size: 20px;
    margin-left: 30px;
    color: green
}
        body{
        background-image: url("/static/bg3.jpg");
       min-height: 100vh;     

/* Center and scale the image nicely */
background-position: center;
background-repeat: no-repeat;
background-size: cover;
    }
    .options{
        font-size: 20px;
        margin: 25px;
        margin-left: 35px;
    }
    .question{
        margin: 20px;
        font-size: 25px;
        font-weight: bold;
    }
    table{
        width: 90%;
        margin: 0 auto;   
        margin-top: 50px; 
        margin-bottom: 50px;
    }
    table tr:nth-child(odd){
        background-color: green;
        color: white;
        height: 30px;
    }
    table tr:nth-child(even){
        background-color: lightgreen;
        height: 30px;
    }
    table tr:first-child{
        background-color: #f64C72;
    }
    table td{
        text-align: center;
        padding: 10px;
    }
    table th{
      padding:8px ;
    }
    span{
        color: #f64C72;
        font-weight: bold ;
    }
    h1{
        text-align: center;
        color: green;
        font-size: 50px;
        margin-top: 60px;
        text-decoration: underline;
    }
    p{
        text-align: center;
        font-size: 25px;
        margin-top: 20px;
    }
    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ots Test paper</title>
</head>
<body>
    <section id="header">
        <p class="logo">OnLine <br>Ex@min@tion<br> SysTem</p>
        <div id="search-bar">
        </ul>
    </div>
        <ul id="navbar">
            <li><a href="{%url 'ots:welcome' %}">Home</a>
            <li><a href="{%url 'ots:registrationForm' %}">Signup</a>
            <li><a href="{%url 'ots:logout' %}">Logout</a>
            </ul>
        </section>
<h1>Your Report Card</h1>
<p>Hi <span>{{candidate.name}}</span>, you have attempted in total <span>{{candidate.test_attempted}} </span>and you have scored <span>{{candidate.points}}</span> on the scale of 10
</p>
<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>
    {%for r in results%}
            <tr>
                <td>{{r.date}}</td>
                <td>{{r.time}}</td>
                <td>{{r.attempt}}</td>
                <td>{{r.right}}</td>
                <td>{{r.wrong}}</td>
                <td>{{r.points}}</td>
            </tr> 
            {%endfor%}
</table>

proj/ots/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        *{
            margin: 0;
            box-sizing: border-box;
        }
        body{
        background-image: url("/static/bg3.jpg");
       min-height: 100vh;     

/* Center and scale the image nicely */
background-position: center;
background-repeat: no-repeat;
background-size: cover;
    }
    #header{
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding-left: 0px ;
    padding-top: 20px;
    padding-bottom: 30px;
    background-color: aliceblue;
    box-shadow: 0 5px 15 px regba(0,0,0,0.6);
    /*to make navbar sticky*/
    z-index: 999;
    position: sticky;
    top:0;
    left:0;
}
#navbar{
    display: flex;
    align-items: center;
    justify-content: center;
}
#navbar li {
    text-decoration: none;
    list-style: none;
    padding: 0 100px;
    
}
#navbar li a{
    display: flex;
    text-decoration: none;
    font-size: 18px;
    font-weight: 600;
    color: #f64C72;
    transition: 0.3s ease;
    font-size: 25px;
}
#navbar li a:hover{
    color: darkblue;
}
.logo{
   font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-weight: bold;
    font-size: 20px;
    margin-left: 30px;
    color: green;
    
}
.bu{
    padding: 10px;
    padding-bottom: 30px;
}
.button-link{
    text-align: center;
    margin-left: 0 auto;
    padding-bottom: 40px;
}
#head{
    text-align: center;
    padding: 50px;
    font-size: 40px;
}
.test,.t{
    text-decoration: none;
    font-size: 30px;
    color: green;
    font-weight: bold;
    font-style: italic;
    text-decoration: underline;
}
span{
    color: #f64C72;
}
    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <section id="header">
        <p class="logo">OnLine <br>Ex@min@tion<br> SysTem</p>
        <div id="search-bar">
        </ul>
    </div>
        <ul id="navbar">
            <li><a href="{%url 'ots:welcome' %}">Home</a>
            <li><a href="{%url 'ots:registrationForm' %}">Signup</a>
            <li><a href="{%url 'ots:logout' %}">Logout</a>
            </ul>
    </section>

        </div>
    </div>
    <div class="content">
    </div>

</body>
</html>
<h1 id="head">Welcome <span>{{request.session.name}},</span> to your homepage</h1>
<div class="bu">
<div class="button-link">
    <a href="{%url 'ots:testpaper' %}?n=5" class="test">Test of 5 questions</a>
</div>
<div class="button-link">
    <a href="{%url 'ots:testpaper' %}?n=6 " class="test">Test of 6 questions</a>
</div>
<div class="button-link">
    <a href="{%url 'ots:testpaper' %}?n=3" class="test">Test of 3 questions</a>
</div>
<div class="button-link">
    <a href="{%url 'ots:testpaper' %}?n=7" class="test">Test of 7 questions</a>
</div>
<div class="button-link">
    <a href="{%url 'ots:testpaper' %}?n=4" class="test">Test of 4 questions</a>
</div>

<div class="button-link">
    <a href="{% url 'ots:testHistory' %}" class="t">Test History</a>
</div>
</div>

proj/ots/templates/login.html
{%include 'master.html'%}
{%block title%}
{%endblock%}
{%block top%}
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" />
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" />
<script src="https://kit.fontawesome.com/6d07541292.js" crossorigin="anonymous"></script>

<style>
    *{
    margin: 0px;
    padding: 0px;
    box-sizing: border-box;
    font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
    body{
        background-image: url("/static/bg3.jpg");
       min-height: 100vh;     

/* Center and scale the image nicely */
background-position: center;
background-repeat: no-repeat;
background-size: cover;
    }
    .container{
        position: relative;
        width: 70vh;
        background-color: #fff;
        height: 80vh;
        border-radius: 15px;
        box-shadow: 0 4px 20px 0 rgba(0,0,0,0.3);
        margin-left: 500px;
        margin-top: 50px;
    }
    .container::before{
        content: "";
        position: absolute;
        top:0;
        width:100%;
        height:100%;
        background:linear-gradient(-45deg,blue,aliceblue);
    }
    .signup-signin{
        position: absolute;
        top:0;
        left:0;
        width: 100%;
        height: 100%;
        display: flex;
        justify-content: space-around;
        align-items: center;

    }
    form{
        display: flex;
        justify-content: center;
        flex-direction: column;
        align-items: center;
        width: 70%;
        min-width: 238px;
        padding: 0 10px;
    }
    .title{
        font-size: 35px;
        color: black;
        margin-bottom: 10px;
    }
    .input-field{
        width: 100%;
        height: 50px;
        background: #f0f0f0;
        margin: 10px 0;
        border: 2px solid aliceblue;
        border-radius: 50px;
        display: flex;
        align-items: center;
        padding: 15px;
    }
    .input-field i{
        padding-right: 15px;
        color: grey;
        font-size: 18px;
    }
    .input-field input{
        outline: none;
        width: 100%;
        font-weight: 600;
        color: #444;
        border: none;
        background-color: #f0f0f0;
    }
    .btn{
        width: 150px;
        height: 50px;
        border: none;
        border-radius: 50px;
        background: blue;
        color: #ffff;
        font-weight: 600;
        margin: 10px 0;
        text-transform: uppercase;
    }
    .btn:hover{
        background-color: darkblue;
    }
    .social-text{
        margin: 10px 0;
        font-size: 16px;
        
    }
    .social-media{
        display: flex;
        justify-content: center;
    }
    .social-icon{
        height: 45px;
        width: 45px;
        display: flex;
        align-items: center;
        justify-content: center;
        color: #444;
        border: 1px solid #444;
        border-radius: 50px;
        margin: 0 5px;
        cursor: pointer;
        background-color: #f0f0f0;
    }
    a{
        text-decoration: none;
    }
    .social-icon:hover{
        color: blue;
    }
    .panel-container{
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .new a:hover{
        color: beige;
    }
</style>
{%endblock%}
{%block content%}

<div class="all-forms">
    {% if loginError %}
    <div id="error">
        {{loginError}}
    </div>
    </div>
    {%endif%}
    <div class="container">
        <div class="signup-signin">
    <form action="{%url 'ots:login' %}" method="POST" class="signin-form">
       {% csrf_token %}
       <h2 class="title">Sign In</h2>
       <div class="input-field">
        <i class="fas fa-user"></i>
        <input type="text"  name="username" placeholder="Username" autocomplete="off">
       </div>
       <div class="input-field">
        <i class="fas fa-lock"></i>
        <input type="password"  name="password" placeholder="Password" autocomplete="off">
       </div>
       <div class="form-unit">
       <input type="submit" value="Login" class="btn">
       <p class="social-text">Or sign in with social platform</p>
       <div class="social-media">
        <a href="#" class="social-icon">
            <i class="fab fa-facebook"></i>
        </a>
        <a href="#" class="social-icon">
            <i class="fab fa-google"></i>
        </a>
        <a href="#" class="social-icon">
            <i class="fab fa-linkedin-in"></i>
        </a>
       </div><br>
       <div class="new">
       New user? &nbsp;<a href="{%url 'ots:registrationForm' %}">Clich here</a>
    </div>
    </div>
    </form>
</div>
</div>
    
{%endblock%}

proj/ots/templates/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        *{
            margin: 0;
            box-sizing: border-box;
        }
    #header{
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding-left: 0px ;
    padding-top: 20px;
    padding-bottom: 30px;
    background-color: aliceblue;
    box-shadow: 0 5px 15 px regba(0,0,0,0.6);
    /*to make navbar sticky*/
    z-index: 999;
    position: sticky;
    top:0;
    left:0;
}
#navbar{
    display: flex;
    align-items: center;
    justify-content: center;
}
#navbar li {
    text-decoration: none;
    list-style: none;
    padding: 0 35px;
    
}
#navbar li a{
    display: flex;
    text-decoration: none;
    font-size: 25px;
    font-weight: 600;
    color: #f64C72;
    transition: 0.3s ease;
}
#navbar li a:hover{
    color: darkblue;
}
.logo{
   font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-weight: bold;
    font-size: 20px;
    margin-left: 30px;
    color: green;
}
    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%} {%endblock%}</title>
</head>
<body>
    {%block top%}
    <section id="header">
        <p class="logo">OnLine <br>Ex@min@tion<br> SysTem</p>
        <div id="search-bar">
        </ul>
    </div>
        <ul id="navbar">
            <li><a href="{%url 'ots:welcome' %}">Home</a>
            <li><a href="{%url 'ots:registrationForm' %}">SignUp</a>
            <li><a href="{%url 'ots:login' %}">Login</a>
               
            </ul>
    </section>
{%endblock%}
        </div>
    </div>
    <div class="content">
        {%block content%}
        {%endblock%}
    </div>

</body>
</html>

proj/ots/templates/show_result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        *{
            margin: 0;
            box-sizing: border-box;
        }
        body{
        background-image: url("/static/bg3.jpg");
       min-height: 100vh;     

/* Center and scale the image nicely */
background-position: center;
background-repeat: no-repeat;
background-size: cover;
    }
    #header{
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding-left: 0px ;
    padding-top: 20px;
    padding-bottom: 30px;
    background-color: aliceblue;
    box-shadow: 0 5px 15 px regba(0,0,0,0.6);
    /*to make navbar sticky*/
    z-index: 999;
    position: sticky;
    top:0;
    left:0;
}
#navbar{
    display: flex;
    align-items: center;
    justify-content: center;
}
#navbar li {
    text-decoration: none;
    list-style: none;
    padding: 0 100px;
    
}
#navbar li a{
    display: flex;
    text-decoration: none;
    font-size: 25px;
    font-weight: 600;
    color: #f64C72;
    transition: 0.3s ease;
}
#navbar li a:hover{
    color: darkblue;
}
.logo{
   font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-weight: bold;
    font-size: 20px;
    margin-left: 30px;
    color: green;
    
}
.bu{
    padding: 10px;
    padding-bottom: 30px;
}
.button-link{
    text-align: center;
    margin-left: 0 auto;
    padding-bottom: 40px;
}
#head{
    text-align: center;
    padding: 50px;
    font-size: 50px;
}
.test{
    text-decoration: none;
    font-size: 30px;
    color: darkblue;
    font-weight: bold;
    font-style: italic;
}

table{
        width: 90%;
        margin: 0 auto;   
        margin-top: 50px; 
        margin-bottom: 100px;
    }
    table tr:nth-child(odd){
        background-color: green;
        color: white;
        height: 30px;
    }
    table tr:nth-child(even){
        background-color: lightgreen;
        height: 30px;
    }
    table tr:first-child{
        background-color: #f64C72;
    }
    table td{
        height: 100px;
        text-align: center;
        padding: 10px;
        color: white;
        background-color: green;
    }
    table th{
        height: 50px;
      padding:10px ;
    }
    span{
        color: #f64C72;
        font-weight: bold ;
    }
    h1{
        text-align: center;
        color: green;
        font-size: 50px;
        margin-top: 60px;
        text-decoration: underline;
    }
    p{
        text-align: center;
        font-size: 25px;
        margin-top: 20px;
    }
    .test,.t{
      
        border-radius: 30px;
        padding: 30px;
    text-decoration: none;
    font-size: 30px;
    color: green;
    font-weight: bold;
    font-style: italic;
    background-color: #f64C72;
    color: white;
}
.t:hover{
    background-color: green;
    
}
    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <section id="header">
        <p class="logo">OnLine <br>Ex@min@tion<br> SysTem</p>
        <div id="search-bar">
        </ul>
    </div>
        <ul id="navbar">
            <li><a href="{%url 'ots:welcome' %}">Home</a>
            <li><a href="{%url 'ots:registrationForm' %}">Signup</a>
            <li><a href="{%url 'ots:logout' %}">Logout</a>
            </ul>
    </section>

        </div>
    </div>
    <div class="content">
        <table>
            <tr>
                <th>Date</th>
                <th>Time</th>
                <th>Attempt</th>
                <th>Right</th>
                <th>Wrong</th>
                <th>Points</th>
            </tr>
            {%for r in results%}
            <tr>
                <td>{{r.date}}</td>
                <td>{{r.time}}</td>
                <td>{{r.attempt}}</td>
                <td>{{r.right}}</td>
                <td>{{r.wrong}}</td>
                <td>{{r.points}}</td>
            </tr> 
            {%endfor%}
        </table>
    </div>
    <div class="button-link">
        <a href="{% url 'ots:testHistory' %}" class="t">Test History</a>
    </div>
</body>
</html>

proj/ots/templates/test_paper.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        *{
            margin: 0;
            box-sizing: border-box;
        }
    #header{
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding-left: 0px ;
    padding-top: 20px;
    padding-bottom: 30px;
    background-color: aliceblue;
    box-shadow: 0 5px 15 px regba(0,0,0,0.6);
    /*to make navbar sticky*/
    z-index: 999;
    position: sticky;
    top:0;
    left:0;
}
#navbar{
    display: flex;
    align-items: center;
    justify-content: center;
}
#navbar li {
    text-decoration: none;
    list-style: none;
    padding: 0 100px;
    
}
#navbar li a{
    display: flex;
    text-decoration: none;
    font-size: 25px;
    font-weight: 600;
    color: #f64C72;
    transition: 0.3s ease;
}
#navbar li a:hover{
    color: darkblue;
}
.logo{
   font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-weight: bold;
    font-size: 20px;
    margin-left: 30px;
    color: green;
}
        body{
        background-image: url("/static/bg3.jpg");
       min-height: 100vh;     

/* Center and scale the image nicely */
background-position: center;
background-repeat: no-repeat;
background-size: cover;
    }
    .options{
        font-size: 20px;
        margin: 25px;
        margin-left: 35px;
    }
    .question{
        margin: 20px;
        font-size: 25px;
        font-weight: bold;
    
    }
    .bt{
        padding: 20px;
        margin-left: 500px;
    }
    .but{
        height:40px;
       width: 50%;
       background-color:green;
       color: white;
       font-weight: bold;
       font-size: 20px;
       border: none;
       outline: none;
       border-radius: 5px;
    }
    .but:hover{
        background-color: #f64C72;
    }
    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ots Test paper</title>
</head>
<body>
    <section id="header">
        <p class="logo">OnLine <br>Ex@min@tion<br> SysTem</p>
        <div id="search-bar">
        </ul>
    </div>
        <ul id="navbar">
            <li><a href="{%url 'ots:welcome' %}">Home</a>
            <li><a href="{%url 'ots:registrationForm' %}">Signup</a>
            <li><a href="{%url 'ots:logout' %}">Logout</a>
            </ul>
        </section>
  <form action="{%url 'ots:calculate_test' %}" method="post">
    {%csrf_token%}
    <div class="qu">
    {%for question in questions%}
    <div class="question">
        <input type="hidden" value="{{question.q_id}}" name="qno{{question.q_id}}" class="qu">{{question.que}}
    </div>
        <div class="options">
        <input type="radio" name="q{{question.q_id}}" value="a">{{question.a}}</div>
        <div class="options"><input type="radio" name="q{{question.q_id}}" value="b">{{question.b}}</div>
        <div class="options"><input type="radio" name="q{{question.q_id}}" value="c">{{question.c}}</div>
        <div class="options"><input type="radio" name="q{{question.q_id}}" value="d">{{question.d}}
    </div>
    {%endfor%}
</div>
    <div class="bt"><input type="submit" value="Submit" class="but"></div>
  </form>
  